export const REGIONS_LIST_REQUEST = 'REGIONS_LIST_REQUEST';
export const REGIONS_LIST_SUCCESS = 'REGIONS_LIST_SUCCESS';
export const REGIONS_LIST_FAIL = 'REGIONS_LIST_FAIL';

export const COMMUNE_BY_REGIONID_LIST_REQUEST = 'COMMUNE_BY_REGIONID_LIST_REQUEST';
export const COMMUNE_BY_REGIONID_LIST_SUCCESS = 'COMMUNE_BY_REGIONID_LIST_SUCCESS';
export const COMMUNE_BY_REGIONID_LIST_FAIL = 'COMMUNE_BY_REGIONID_LIST_FAIL';